name: DAFT Func

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Check out daft-func repository
        uses: actions/checkout@v2
        with:
          repository: meroxa/daft-func
          token: ${{ secrets.DAFT_FUNC_ACCESS_TOKEN}}
      -
        name: Check out this repository
        uses: actions/checkout@v2
        with:
          path: ./lib/function-deploy/data-app
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./lib/function-deploy
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.sha }}:latest
