name: Funcky Town

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Check out functions repository
        uses: actions/checkout@v2
        with:
          repository: meroxa/funcky-town
          token: ${{ secrets.FUNCKY_TOWN_ACCESS_TOKEN}}
      -
        name: Check out this repository
        uses: actions/checkout@v2
        with:
          path: data-app
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-funtime-sample:latest
